"""
HireWise AI — Synthetic Test Candidates
=========================================
Six synthetic candidates for unit testing:
  1. Strong production retrieval engineer (should rank #1)
  2. Keyword-stuffing marketing profile (should receive penalties)
  3. Pure academic/research profile (should rank lower)
  4. Inactive but technically strong profile
  5. Suspicious honeypot profile
  6. Product-focused retrieval engineer (startup experience)
"""

from __future__ import annotations

STRONG_RETRIEVAL_ENGINEER: dict = {
    "candidate_id": "CAND_9990001",
    "profile": {
        "anonymized_name": "Alex Production",
        "headline": "Senior ML Engineer | Vector Search | Ranking Systems | Elasticsearch",
        "summary": "7 years building production search and ranking systems. Deployed Elasticsearch hybrid search, FAISS vector indexes, and NDCG-based offline evaluation pipelines at scale. Currently leading the retrieval team at a Series B startup.",
        "location": "Pune",
        "country": "India",
        "years_of_experience": 7.0,
        "current_title": "Senior ML Engineer",
        "current_company": "SearchCo",
        "current_company_size": "51-200",
        "current_industry": "Technology",
    },
    "career_history": [
        {
            "company": "SearchCo",
            "title": "Senior ML Engineer",
            "start_date": "2022-01-01",
            "end_date": None,
            "duration_months": 30,
            "is_current": True,
            "industry": "Technology",
            "company_size": "51-200",
            "description": "Built and deployed a FAISS-based vector search index serving 50M queries/day. Designed the hybrid retrieval pipeline combining BM25 (Elasticsearch) with dense embeddings using sentence-transformers. Implemented NDCG and MRR offline evaluation frameworks. Owned A/B testing infrastructure for ranking improvements. Shipped 3 major ranking model upgrades using LambdaMART.",
        },
        {
            "company": "DataSearch Inc",
            "title": "ML Engineer",
            "start_date": "2018-06-01",
            "end_date": "2021-12-01",
            "duration_months": 42,
            "is_current": False,
            "industry": "Technology",
            "company_size": "201-500",
            "description": "Developed and maintained production Python retrieval pipelines using Elasticsearch. Built candidate matching and recommendation systems for an HR-tech platform. Deployed sentence-transformer-based semantic search reducing zero-result queries by 40%. Monitored model drift and maintained SLA on inference latency.",
        },
    ],
    "education": [
        {
            "institution": "IIT Bombay",
            "degree": "B.Tech",
            "field_of_study": "Computer Science",
            "start_year": 2013,
            "end_year": 2017,
            "grade": "8.9 CGPA",
            "tier": "tier_1",
        }
    ],
    "skills": [
        {"name": "Elasticsearch", "proficiency": "expert", "endorsements": 45, "duration_months": 48},
        {"name": "FAISS", "proficiency": "expert", "endorsements": 38, "duration_months": 30},
        {"name": "Python", "proficiency": "expert", "endorsements": 60, "duration_months": 72},
        {"name": "Sentence Transformers", "proficiency": "advanced", "endorsements": 22, "duration_months": 24},
        {"name": "NDCG", "proficiency": "advanced", "endorsements": 15, "duration_months": 30},
        {"name": "LambdaMART", "proficiency": "advanced", "endorsements": 10, "duration_months": 20},
    ],
    "certifications": [],
    "languages": [{"language": "English", "proficiency": "professional"}],
    "redrob_signals": {
        "profile_completeness_score": 92.0,
        "signup_date": "2024-01-01",
        "last_active_date": "2026-05-01",
        "open_to_work_flag": True,
        "profile_views_received_30d": 50,
        "applications_submitted_30d": 3,
        "recruiter_response_rate": 0.85,
        "avg_response_time_hours": 12.0,
        "skill_assessment_scores": {"Python": 90, "Elasticsearch": 88},
        "connection_count": 800,
        "endorsements_received": 120,
        "notice_period_days": 30,
        "expected_salary_range_inr_lpa": {"min": 35.0, "max": 55.0},
        "preferred_work_mode": "hybrid",
        "willing_to_relocate": True,
        "github_activity_score": 78.0,
        "search_appearance_30d": 200,
        "saved_by_recruiters_30d": 15,
        "interview_completion_rate": 0.95,
        "offer_acceptance_rate": 0.80,
        "verified_email": True,
        "verified_phone": True,
        "linkedin_connected": True,
    },
}


KEYWORD_STUFFING_MARKETING: dict = {
    "candidate_id": "CAND_9990002",
    "profile": {
        "anonymized_name": "Sam Stuffer",
        "headline": "Marketing Manager | AI Expert | Vector Search | FAISS | Elasticsearch | NDCG | LTR",
        "summary": "I've been curious about how AI tools could augment my work. Experimented with ChatGPT and a few other tools for productivity. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.",
        "location": "Mumbai",
        "country": "India",
        "years_of_experience": 6.0,
        "current_title": "Marketing Manager",
        "current_company": "BrandCo",
        "current_company_size": "201-500",
        "current_industry": "Marketing",
    },
    "career_history": [
        {
            "company": "BrandCo",
            "title": "Marketing Manager",
            "start_date": "2020-01-01",
            "end_date": None,
            "duration_months": 53,
            "is_current": True,
            "industry": "Marketing",
            "company_size": "201-500",
            "description": "Managed brand campaigns and content strategy. Wrote blog posts about AI trends. Used ChatGPT for content drafting. Organised marketing events and managed social media accounts.",
        },
    ],
    "education": [
        {
            "institution": "Local College",
            "degree": "B.Com",
            "field_of_study": "Commerce",
            "start_year": 2012,
            "end_year": 2015,
            "grade": "65%",
            "tier": "tier_4",
        }
    ],
    "skills": [
        {"name": "FAISS", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Elasticsearch", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "NDCG", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Vector Search", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Learning to Rank", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Sentence Transformers", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Milvus", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Pinecone", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Marketing", "proficiency": "expert", "endorsements": 25, "duration_months": 60},
        {"name": "Content Writing", "proficiency": "expert", "endorsements": 18, "duration_months": 50},
    ],
    "certifications": [],
    "languages": [{"language": "English", "proficiency": "professional"}],
    "redrob_signals": {
        "profile_completeness_score": 45.0,
        "signup_date": "2025-01-01",
        "last_active_date": "2025-06-01",
        "open_to_work_flag": True,
        "profile_views_received_30d": 5,
        "applications_submitted_30d": 10,
        "recruiter_response_rate": 0.20,
        "avg_response_time_hours": 200.0,
        "skill_assessment_scores": {},
        "connection_count": 100,
        "endorsements_received": 10,
        "notice_period_days": 60,
        "expected_salary_range_inr_lpa": {"min": 10.0, "max": 15.0},
        "preferred_work_mode": "remote",
        "willing_to_relocate": False,
        "github_activity_score": -1,
        "search_appearance_30d": 20,
        "saved_by_recruiters_30d": 2,
        "interview_completion_rate": 0.40,
        "offer_acceptance_rate": -1,
        "verified_email": False,
        "verified_phone": False,
        "linkedin_connected": False,
    },
}


PURE_ACADEMIC: dict = {
    "candidate_id": "CAND_9990003",
    "profile": {
        "anonymized_name": "Dr. Research Only",
        "headline": "AI Researcher | NLP | Information Retrieval | Publications",
        "summary": "PhD in Information Retrieval with 6 papers published in top venues. Research focus on learning-to-rank algorithms and neural information retrieval. No production engineering experience.",
        "location": "Bengaluru",
        "country": "India",
        "years_of_experience": 8.0,
        "current_title": "AI Researcher",
        "current_company": "University Research Lab",
        "current_company_size": "1001-5000",
        "current_industry": "Education",
    },
    "career_history": [
        {
            "company": "University Research Lab",
            "title": "AI Researcher",
            "start_date": "2019-09-01",
            "end_date": None,
            "duration_months": 80,
            "is_current": True,
            "industry": "Education",
            "company_size": "1001-5000",
            "description": "Conducted research on neural ranking models for information retrieval. Published papers on BERT-based ranking. Supervised PhD students. Participated in TREC evaluation challenges. Never deployed code to production systems.",
        },
    ],
    "education": [
        {
            "institution": "IISC",
            "degree": "PhD",
            "field_of_study": "Information Retrieval",
            "start_year": 2015,
            "end_year": 2019,
            "grade": "A+",
            "tier": "tier_1",
        }
    ],
    "skills": [
        {"name": "Python", "proficiency": "advanced", "endorsements": 20, "duration_months": 60},
        {"name": "Information Retrieval", "proficiency": "expert", "endorsements": 15, "duration_months": 80},
        {"name": "Neural Ranking", "proficiency": "expert", "endorsements": 10, "duration_months": 60},
    ],
    "certifications": [],
    "languages": [{"language": "English", "proficiency": "professional"}],
    "redrob_signals": {
        "profile_completeness_score": 70.0,
        "signup_date": "2024-06-01",
        "last_active_date": "2026-04-01",
        "open_to_work_flag": False,
        "profile_views_received_30d": 30,
        "applications_submitted_30d": 1,
        "recruiter_response_rate": 0.50,
        "avg_response_time_hours": 72.0,
        "skill_assessment_scores": {},
        "connection_count": 200,
        "endorsements_received": 30,
        "notice_period_days": 90,
        "expected_salary_range_inr_lpa": {"min": 30.0, "max": 50.0},
        "preferred_work_mode": "onsite",
        "willing_to_relocate": False,
        "github_activity_score": 15.0,
        "search_appearance_30d": 40,
        "saved_by_recruiters_30d": 5,
        "interview_completion_rate": 0.70,
        "offer_acceptance_rate": -1,
        "verified_email": True,
        "verified_phone": False,
        "linkedin_connected": True,
    },
}


INACTIVE_STRONG_TECHNICAL: dict = {
    "candidate_id": "CAND_9990004",
    "profile": {
        "anonymized_name": "Jamie Inactive",
        "headline": "ML Engineer | Search Infrastructure | On Sabbatical",
        "summary": "6 years of strong production search infrastructure. Built and deployed Elasticsearch at scale. Currently on a career break.",
        "location": "Noida",
        "country": "India",
        "years_of_experience": 6.0,
        "current_title": "ML Engineer",
        "current_company": "On Sabbatical",
        "current_company_size": "1-10",
        "current_industry": "Technology",
    },
    "career_history": [
        {
            "company": "SearchStartup",
            "title": "Senior ML Engineer",
            "start_date": "2018-01-01",
            "end_date": "2024-01-01",
            "duration_months": 72,
            "is_current": False,
            "industry": "Technology",
            "company_size": "51-200",
            "description": "Deployed and maintained Elasticsearch-based retrieval systems. Built vector search infrastructure using FAISS. Implemented online A/B testing for ranking improvements. Owned the search quality evaluation pipeline with NDCG and MRR metrics.",
        },
    ],
    "education": [
        {
            "institution": "BITS Pilani",
            "degree": "B.E.",
            "field_of_study": "Computer Science",
            "start_year": 2012,
            "end_year": 2016,
            "grade": "8.5 CGPA",
            "tier": "tier_1",
        }
    ],
    "skills": [
        {"name": "Elasticsearch", "proficiency": "expert", "endorsements": 30, "duration_months": 60},
        {"name": "FAISS", "proficiency": "advanced", "endorsements": 20, "duration_months": 36},
        {"name": "Python", "proficiency": "expert", "endorsements": 45, "duration_months": 72},
    ],
    "certifications": [],
    "languages": [{"language": "English", "proficiency": "professional"}],
    "redrob_signals": {
        "profile_completeness_score": 65.0,
        "signup_date": "2023-01-01",
        "last_active_date": "2024-06-01",  # 12+ months ago
        "open_to_work_flag": False,
        "profile_views_received_30d": 10,
        "applications_submitted_30d": 0,
        "recruiter_response_rate": 0.30,
        "avg_response_time_hours": 120.0,
        "skill_assessment_scores": {},
        "connection_count": 400,
        "endorsements_received": 60,
        "notice_period_days": 0,
        "expected_salary_range_inr_lpa": {"min": 40.0, "max": 65.0},
        "preferred_work_mode": "hybrid",
        "willing_to_relocate": True,
        "github_activity_score": 5.0,
        "search_appearance_30d": 25,
        "saved_by_recruiters_30d": 3,
        "interview_completion_rate": 0.85,
        "offer_acceptance_rate": 0.90,
        "verified_email": True,
        "verified_phone": True,
        "linkedin_connected": True,
    },
}


HONEYPOT_PROFILE: dict = {
    "candidate_id": "CAND_9990005",
    "profile": {
        "anonymized_name": "Perfect Honeypot",
        "headline": "Senior AI Engineer | Vector Search | Elasticsearch | FAISS | Milvus | NDCG | LambdaMART | LoRA",
        "summary": "I've been curious about how AI tools could augment my work. I've experimented with ChatGPT and a few other tools for productivity and content creation. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.",
        "location": "Pune",
        "country": "India",
        "years_of_experience": 7.0,
        "current_title": "HR Manager",
        "current_company": "RecruiterCo",
        "current_company_size": "51-200",
        "current_industry": "Human Resources",
    },
    "career_history": [
        {
            "company": "RecruiterCo",
            "title": "HR Manager",
            "start_date": "2018-01-01",
            "end_date": None,
            "duration_months": 100,
            "is_current": True,
            "industry": "Human Resources",
            "company_size": "51-200",
            "description": "Managed HR operations, recruitment processes, and employee onboarding. Organised team building activities. Maintained HR databases and employee records.",
        },
    ],
    "education": [
        {
            "institution": "Local College",
            "degree": "B.A.",
            "field_of_study": "Human Resources",
            "start_year": 2010,
            "end_year": 2013,
            "grade": "70%",
            "tier": "tier_4",
        }
    ],
    "skills": [
        {"name": "FAISS", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Elasticsearch", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Milvus", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "NDCG", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "LambdaMART", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "LoRA", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Vector Search", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Sentence Transformers", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "BGE Embeddings", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "Pinecone", "proficiency": "expert", "endorsements": 0, "duration_months": 0},
        {"name": "HR Management", "proficiency": "expert", "endorsements": 30, "duration_months": 84},
    ],
    "certifications": [],
    "languages": [{"language": "English", "proficiency": "professional"}],
    "redrob_signals": {
        "profile_completeness_score": 80.0,
        "signup_date": "2025-06-01",
        "last_active_date": "2025-05-01",  # signup AFTER last_active → integrity flag!
        "open_to_work_flag": True,
        "profile_views_received_30d": 100,
        "applications_submitted_30d": 50,
        "recruiter_response_rate": 0.90,
        "avg_response_time_hours": 1.0,
        "skill_assessment_scores": {},
        "connection_count": 1000,
        "endorsements_received": 5,
        "notice_period_days": 0,
        "expected_salary_range_inr_lpa": {"min": 30.0, "max": 60.0},
        "preferred_work_mode": "hybrid",
        "willing_to_relocate": True,
        "github_activity_score": 95.0,
        "search_appearance_30d": 500,
        "saved_by_recruiters_30d": 50,
        "interview_completion_rate": 1.0,
        "offer_acceptance_rate": 1.0,
        "verified_email": True,
        "verified_phone": True,
        "linkedin_connected": True,
    },
}


PRODUCT_RETRIEVAL_ENGINEER: dict = {
    "candidate_id": "CAND_9990006",
    "profile": {
        "anonymized_name": "Rivera Product",
        "headline": "ML Engineer | Candidate Matching | Recommendation Systems | HR-Tech",
        "summary": "5 years building recommendation and matching systems at a product startup. Shipped candidate-job matching using dense retrieval (FAISS + sentence-transformers). Owned the ranking pipeline end-to-end.",
        "location": "Noida",
        "country": "India",
        "years_of_experience": 5.5,
        "current_title": "ML Engineer",
        "current_company": "HRTech Startup",
        "current_company_size": "11-50",
        "current_industry": "HR Technology",
    },
    "career_history": [
        {
            "company": "HRTech Startup",
            "title": "ML Engineer",
            "start_date": "2021-03-01",
            "end_date": None,
            "duration_months": 39,
            "is_current": True,
            "industry": "HR Technology",
            "company_size": "11-50",
            "description": "Designed and shipped the candidate-job matching pipeline using FAISS for dense retrieval. Built the recommendation system ranking 10K candidates per job posting. Implemented offline evaluation with NDCG@10 and MRR. Deployed sentence-transformer models for semantic job matching. Owned the full ML stack from feature engineering to serving.",
        },
        {
            "company": "DataCo",
            "title": "Data Scientist",
            "start_date": "2019-06-01",
            "end_date": "2021-02-01",
            "duration_months": 20,
            "is_current": False,
            "industry": "Technology",
            "company_size": "201-500",
            "description": "Built recommendation systems for e-commerce platform. Developed Python pipelines for feature engineering and model training. Deployed collaborative filtering models to production.",
        },
    ],
    "education": [
        {
            "institution": "NIT Trichy",
            "degree": "B.Tech",
            "field_of_study": "Computer Science",
            "start_year": 2015,
            "end_year": 2019,
            "grade": "8.2 CGPA",
            "tier": "tier_2",
        }
    ],
    "skills": [
        {"name": "FAISS", "proficiency": "advanced", "endorsements": 12, "duration_months": 36},
        {"name": "Python", "proficiency": "expert", "endorsements": 30, "duration_months": 60},
        {"name": "Sentence Transformers", "proficiency": "advanced", "endorsements": 8, "duration_months": 30},
        {"name": "Recommendation Systems", "proficiency": "advanced", "endorsements": 18, "duration_months": 48},
        {"name": "NDCG", "proficiency": "intermediate", "endorsements": 5, "duration_months": 36},
    ],
    "certifications": [],
    "languages": [{"language": "English", "proficiency": "professional"}],
    "redrob_signals": {
        "profile_completeness_score": 88.0,
        "signup_date": "2024-03-01",
        "last_active_date": "2026-05-15",
        "open_to_work_flag": True,
        "profile_views_received_30d": 40,
        "applications_submitted_30d": 5,
        "recruiter_response_rate": 0.75,
        "avg_response_time_hours": 24.0,
        "skill_assessment_scores": {"Python": 85},
        "connection_count": 450,
        "endorsements_received": 55,
        "notice_period_days": 45,
        "expected_salary_range_inr_lpa": {"min": 25.0, "max": 40.0},
        "preferred_work_mode": "hybrid",
        "willing_to_relocate": True,
        "github_activity_score": 55.0,
        "search_appearance_30d": 80,
        "saved_by_recruiters_30d": 8,
        "interview_completion_rate": 0.90,
        "offer_acceptance_rate": 0.75,
        "verified_email": True,
        "verified_phone": True,
        "linkedin_connected": True,
    },
}

ALL_SYNTHETIC_CANDIDATES = [
    STRONG_RETRIEVAL_ENGINEER,
    KEYWORD_STUFFING_MARKETING,
    PURE_ACADEMIC,
    INACTIVE_STRONG_TECHNICAL,
    HONEYPOT_PROFILE,
    PRODUCT_RETRIEVAL_ENGINEER,
]
